# Default configuration for GSM8K benchmark

# Model configuration
model:
  name: "gpt-3.5-turbo"
  temperature: 0.0
  max_tokens: 1000

# Benchmark settings
benchmark:
  n_samples: 50
  timeout_seconds: 30
  techniques:
    - zero_shot
    - few_shot
    - cot
    - self_consistency
    - prolog_style

# Self-consistency specific settings
self_consistency:
  n_samples: 5
  temperature: 0.7

# Evaluation settings
evaluation:
  accuracy_threshold: 0.01
  save_detailed_predictions: true

# Output settings
output:
  create_visualizations: true
  save_plots: true
  export_csv: true
